### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by jonah-williams** [royratcliffe/ActiveResourceKit#1]
ActiveResourceKit looks interesting however I don't see a license file so I'm reluctant to make use of it. Could you provide your preferred distribution license as a license file or in the readme?

**Comment by royratcliffe** [comment]
Very good point. Thanks. Licensing information appears at the top of each source file. The license is MIT, just like the Ruby counterparts. I've added the license text to the project root as well to make it clearer.

Thanks for enquiring about that.

**Comment by jonah-williams** [comment]
Thanks! I didn't both the check the individual files though it makes lots
of sense to include the license there. I appreciate you making it more
visible for anyone first looking at the project.

On Tue, Jun 12, 2012 at 9:04 PM, Roy Ratcliffe <
reply@reply.github.com

**Comment by royratcliffe** [comment]
You are welcome. But thank you for raising the issue. You are right: best to make it visible at the root.
